### ISSUE TITLE
Backport only if before Win32-2.5.3.0?

### ISSUE THREAD

**Issue by mpilgrem** [RyanGlScott/mintty#1]
I understand that it was `Win32-2.5.3.0` that fixed the ntdll-related problem. Consequently, I wondered if the criteria for not backporting should be: `# if MIN_VERSION_Win32(2,5,3)` rather than the existing `# if MIN_VERSION_Win32(2,5,0)`?

**Comment by RyanGlScott** [comment]
None of `Win32` versions 2.5.0 through 2.5.2 were ever bundled with GHC, so the chances of anyone building against them are quite slim. Still, I suppose it couldn't hurt to be safe here.

**Comment by RyanGlScott** [comment]
I've uploaded [`mintty-0.1.2`](http://hackage.haskell.org/package/mintty-0.1.2) to Hackage with a fix.
