### ISSUE TITLE
Why does mintty depend on filepath?

### ISSUE THREAD

**Issue by Bodigrim** [RyanGlScott/mintty#5]
https://github.com/RyanGlScott/mintty/blob/28fe58c9927ceff2d636a14b780642092d734bf3/mintty.cabal#L69-L70
However I do not see `System.FilePath` to be imported.

**Comment by RyanGlScott** [comment]
A good question. `mintty` used to import `System.FilePath`, but that import was removed in e03176ee725bcc56e28e6622a81cc020d8474d15. It looks like I forgot to remove the `filepath` dependency at the same time.

**Comment by Bodigrim** [comment]
There is an ongoing work on `filepath-2.0`, and it would help to reduce the amount of packages to rebuild when running tests / benchmarks.

**Comment by RyanGlScott** [comment]
I've submitted #6 with a fix.
